name: tonejs
description: A starting point for Dart libraries or applications.
version: 0.0.1
author: Vladislav Gordievskiy

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  func: ^0.1.0
  js: ^0.6.0
  args: any
  path: any
